- README.md
[WIP] needs input/feedback, please comment directly on PR. Closes #1.
> rough draft of initial stories

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/PersonalizationDetail.java
> create PersonlizationDetail model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/PersonalizationDetail.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/User.java
> User model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Profile.java
closes #16 
fyi - @RoyPuja and @shehbashahab
> User profile model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
> create getters and setters for network

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
> Create events model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
> Feature model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
closes #31 
fyi - 
@RoyPuja @shehbashahab
> create post model

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
closes #13 
fyi - 
@RoyPuja @shehbashahab
> add subscribe model

- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
@RoyPuja and @shehbashahab the models are all set and the data is seeded in parse. closes #35 we can definitely seed more data, but we have a good start.
> register classes and set the parse class name

- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesArrayAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/res/layout/fragment_features.xml
- app/src/main/res/layout/item_feature.xml
- app/src/main/res/layout/item_timeline.xml
> Features Timeline Fragment

- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/network/MeetupClient.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/ModelJSONObject.java
> Meetup client

- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsArrayAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/res/layout/fragment_timeline.xml
- app/src/main/res/layout/item_timeline.xml
Initial commits for #23 #20 and #19
> Feature and Timeline Fragments and Adapters

- app/app.iml
- app/build.gradle
- app/src/main/res/layout/item_feature.xml
> Added CardView to Feature Item

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Network.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
- app/src/main/res/layout/fragment_events.xml
- app/src/main/res/layout/item_event.xml
> Events timeline

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
> base case for subscribe/unsubscribe listeners in events

- app/app.iml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/res/layout/activity_feature_detail.xml
Some updates for #23, #22 and #19
> Updates for Features Detail View

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
> Timeline Fragment and Adapter

- .idea/gradle.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/menu/menu_event_details.xml
- app/src/main/res/values/strings.xml
> Events detail view

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
fyi - removing post title from
> Drop title on post. To note: data on parse is updated.

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/PersonalizationQuestionnaire.java
closes https://github.com/WomenWhoCode/WomenWhoCode/issues/73
> locally generated questionnaire

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
> Fixed bug: itemOnClick launches detail view for the wrong item

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
- app/src/main/res/layout/item_feature.xml
> Feature: Update UI to Match Mocks

- .idea/gradle.xml
- .idea/misc.xml
- app/app.iml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/PersonalizationActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/UserProfileActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/SignUpFragment.java
- app/src/main/res/layout/activity_email_login.xml
- app/src/main/res/layout/activity_email_sign_up.xml
- app/src/main/res/layout/activity_userprofile.xml
- app/src/main/res/layout/fragment_signup.xml
> login flow completed

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailActivity.java
> Add Back/Up Button on Feature Detail View

- .idea/gradle.xml
- .idea/misc.xml
- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/LocalDataStore.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/NetworkConnectivityReceiver.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/fragment_events.xml
- app/src/main/res/layout/fragment_features.xml
- app/src/main/res/layout/fragment_timeline.xml
> Local persistance and smarter server requests

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/Utilities.java
- app/src/main/res/layout/item_timeline.xml
> Timeline: Update UI to Match Mocks

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
- app/src/main/res/layout/item_timeline.xml
- app/src/main/res/values/strings.xml
> Rename 'Features' to 'Topics'

- .idea/gradle.xml
- .idea/misc.xml
- app/app.iml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/UserProfileActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/LocalDataStore.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/LocationProvider.java
- app/src/main/res/layout/activity_event_details.xml
> Events by location

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/res/layout/activity_feature_detail.xml
- app/src/main/res/layout/item_post.xml
> Feature: Display Posts in Feature Detail View

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/res/layout/activity_feature_details.xml
- app/src/main/res/layout/fragment_events.xml
- app/src/main/res/layout/item_event.xml
- app/src/main/res/layout/item_feature.xml
> Subscribing

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/activity_feature_details.xml
- app/src/main/res/layout/fragment_chat.xml
> Chatter pager view placeholder

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Awesome.java
- app/src/main/res/layout/item_post.xml
- app/src/main/res/layout/item_timeline.xml
closes #66 functionally, but more elegant solution on the way
> Posts: increment awesome count on posts

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
@shehbashahab and @RoyPuja fyi - this makes it so when you go back with the up, it will take you to the fragment it came from
> Hold states

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/res/layout/item_feature.xml
> dynamically render colors

- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Awesome.java
- app/src/main/res/layout/item_post.xml
- app/src/main/res/layout/item_timeline.xml
> Move awesomeCount processing to background on posts

- app/src/main/res/layout/item_timeline.xml
> Updated item_timeline xml to match mocks

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
- app/src/main/res/layout/item_post.xml
- app/src/main/res/layout/item_timeline.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
> Post timeline

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
> Timeline: Only display posts you are subscribed to

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/res/menu/menu_main.xml
- app/src/main/res/values/strings.xml
> Added intent back to LoginActivity on Logout

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Event.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
> Better counts

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
Partial update - fix for posts on Timeline
Pending - posts in detail views
Relates to #162
> AwesomeCount update for Timeline posts

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Awesome.java
> Another partial update for awesomeCounts on Posts

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/CircleTransform.java
> Made images and image placeholders circular

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/res/values/strings.xml
> Update awesomeCount on UI and Parse when awesomeIcon is clicked

- .idea/gradle.xml
- WomenWhoCode.iml
- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
Used FlipHorizontalTransformer()
closes #176
> Added transition between page swipes

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
> Detail Activities: Add transitions between page swipes

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
Reverts WomenWhoCode/WomenWhoCode#179
> Revert "Detail Activities: Add transitions between page swipes"

- .idea/gradle.xml
- WomenWhoCode.iml
- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
Reverts WomenWhoCode/WomenWhoCode#177
> Revert "Added transition between page swipes"

- .idea/gradle.xml
- WomenWhoCode.iml
- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/ZoomOutPageTransformer.java
> Add transitions between page swipes

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
> Animate when Post is awesomed

- app/src/main/res/layout/activity_email_login.xml
> Center login button in activity_email_login.xml

- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/ChatListAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventPostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Message.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/LocalDataStore.java
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/item_chat.xml
- app/src/main/res/values/strings.xml
chat for events
closes some of #97 
closes #174 
closes #175
> Chat integration

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/UserProfileActivity.java
> Auto subscribe users to features on sign up

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/CircleTransform.java
> Fix for crash when loading feature images in timeline and detail views

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
closes #173
fyi - @shehbashahab
> awesome count bugs

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeatureChatFragment.java
> add features chat

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
> Add transition from Feature/Event -> Detail View

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/widgets/CustomTabStrip.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/widgets/CustomViewPager.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/activity_feature_details.xml
> Only sub can chat

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Awesome.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
> Lint fixes for performance

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/res/values/strings.xml
Functional fix for #198, animation to be added in next commit
> Sends message when enter or send button is pressed

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
> Open navigation drawer onClick of icon in toolbar

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/res/menu/drawer_menu.xml
> Add Logout functionality to navigation drawer

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LaunchActivity.java
- app/src/main/res/layout/activity_launch.xml
> Dispatcher

- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/res/layout/fragment_features.xml
> Recycler view

- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/ChatListAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
> Adapter code tidy with ButterKnife

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
> Fix for crash in EventsAdapter

- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/res/anim/scale_down.xml
- app/src/main/res/anim/scale_up.xml
> Improved awesomeCount animation

- app/src/main/java/com/example/womenwhocode/womenwhocode/ParseApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/UserProfileActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/FeatureTag.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/PersonalizationDetails.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Recommendation.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Subscribe.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Tag.java
> Recommendations

- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/ChatListAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeatureChatFragment.java
- app/src/main/res/layout/item_chat.xml
- app/src/main/res/menu/menu_feature_details.xml
- app/src/main/res/values/strings.xml
> Misc. Chat UI updates

- .idea/gradle.xml
- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Post.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/activity_feature_details.xml
- app/src/main/res/layout/item_event.xml
- app/src/main/res/layout/item_feature.xml
- app/src/main/res/layout/item_timeline.xml
- app/src/main/res/values-v21/styles.xml
> Shared element transitions

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
> increment counter even if data comes back null

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/res/color/checkbox.xml
- app/src/main/res/values/styles.xml
> update checkbox color in lollipop and above, not ideal fix

- app/src/main/res/layout/item_timeline.xml
- app/src/main/res/values/styles.xml
> font alphas and alignment

- app/src/main/res/layout/item_chat.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
> Updated chat bubble UI to match mocks

- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventPostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/viewholders/ViewHolderTopicHeader.java
> Personalized events

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
> add add posts listeners to event details

- app/src/main/res/color/tab_text.xml
- app/src/main/res/layout/activity_timeline.xml
- app/src/main/res/layout/item_event.xml
- app/src/main/res/menu/drawer_menu.xml
- app/src/main/res/values/attrs.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
> Better theming

- app/src/main/res/layout/item_post.xml
- app/src/main/res/layout/item_timeline.xml
> Updated positioning of share button

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/AddPostDialogFragment.java
> Make Add Post Dialog Full Screen

- .idea/gradle.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/res/anim/hold.xml
> Fixed bug with awesome animation

- .idea/gradle.xml
- WomenWhoCode.iml
- app/app.iml
- app/build.gradle
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/ChatListAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/EventsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/AddPostDialogFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/LogInFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/RecommendFeatureDialog.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/widgets/ScrollAwareFABBehavior.java
- app/src/main/res/layout/fragment_question1.xml
- build.gradle
> Lint fixes and performance improvements

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LaunchActivity.java
Removing unused imports from `LaunchActivity.java`
Reference #331
> Removal of unused imports from LaunchActivity.java

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/CustomProgress.java
Refactored uses of deprecated API to ContextCompat.getColor(context,
R.color.color_name)
> Code Maturity Issue: getResources().getColor() is deprecated

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/res/values/strings.xml
Extracting hard coded strings to Strings Resource  .
Work on Issue #337
> Extracting hard coded strings to Strings Resource 

- README.md
All the changes have been made in the new Pull Request. Fixed #326 .
> Added Contribution Guide for Developers

- app/src/main/res/layout/fragment_login.xml
> Removed unused onClick "loginWithEmail" in fragment_login.xml

- app/src/main/java/com/example/womenwhocode/womenwhocode/models/Feature.java
> Fixed incorrect null check on getImageUrl() in Feature class

- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/PersonalizationActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeatureChatFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/RecommendFeatureDialog.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/LocationProvider.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/RoundedImageView.java
> Removed unusued variable assignments

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/res/layout/fragment_events.xml
- app/src/main/res/values/strings.xml
Added functionality to display no events message in case no events are found or the location is not obtained.
> Added No Events Found Message

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/res/layout/activity_email_sign_up.xml
> #355 Snackbar Added

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/UserProfileActivity.java
> Removed redundant look ups to ivPhoto view in UserProfileActivity

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
> Removed duplicate calls to Profile from TimelineActivity

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/res/menu/menu_feature_details.xml
#330 removed chat fragments, removal of pager adapter pending
> Removed chat fragments from Events and Topics

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/res/layout/activity_event_details.xml
- app/src/main/res/layout/activity_feature_details.xml
> Remove ViewPager from Events and Topics

- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/res/drawable/btn_check_off_pressed.xml
- app/src/main/res/drawable/btn_check_on_pressed.xml
- app/src/main/res/drawable/check_box_selector.xml
- app/src/main/res/layout/activity_email_login.xml
- app/src/main/res/layout/activity_email_sign_up.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_signup.xml
> Reformatted code and optimized imports

- app/app.iml
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginActivity.java
> Removed unused override onOptionsItemSelected(MenuItem item)

- app/app.iml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/womenwhocode/womenwhocode/WomenWhoCodeApplication.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LaunchActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/ThemeUtils.java
> Rename ParseApplication to WomenWhoCodeApplication

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/EventsFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/FeaturesFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/TimelineFragment.java
> Refactored uses of deprecated API 'onAttach(android.app.Activity)'

- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/Question1Fragment.java
> Refactor usage of deprecated API 'getDrawable(int)'

- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LaunchActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/java/com/example/womenwhocode/womenwhocode/utils/ThemeUtils.java
> Reformat post code changes

- app/src/main/java/com/womenwhocode/womenwhocode/fragments/EventPostsFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/res/layout/fragment_posts_list.xml
- app/src/main/res/values/strings.xml
> Provide feedback when there are no posts to show in detail views

- app/src/main/java/com/womenwhocode/womenwhocode/fragments/EventPostsFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/FeaturePostsFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/PostsListFragment.java
- app/src/main/res/values/strings.xml
> Moved showPosts() subclass implementations to superclass

- app/src/main/java/com/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/res/menu/drawer_menu.xml
> Add Contact Us functionality

- app/src/main/java/com/womenwhocode/womenwhocode/activities/TimelineActivity.java
> Removed duplicate calls to ParseUser.getCurrentUser()

- app/src/main/java/com/womenwhocode/womenwhocode/activities/UserProfileActivity.java
Fixes #393, sorry for the delay in fixing issues
> User Profile removed from back stack

- app/src/main/java/com/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/PersonalizationActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/UserProfileActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/ChatFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/RecommendFeatureDialog.java
- app/src/main/java/com/womenwhocode/womenwhocode/utils/KeyBoardSupport.java
- app/src/main/res/layout/activity_email_login.xml
- app/src/main/res/layout/activity_userprofile.xml
- app/src/main/res/layout/fragment_question1.xml
> Added Personalized Support for KeyBoard

- app/src/main/java/com/womenwhocode/womenwhocode/activities/LaunchActivity.java
The blank screen was present due to LaunchActivity not being finished after launch of corresponding activity. This fixes issue #371 .
> Removed blank screen due to Launch Activity

- README.md
@zassmin please review
closes #413
> Closes issue #413

- app/src/main/java/com/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
> Login Backstack removed

- app/src/main/java/com/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/res/values/strings.xml
Error messages displayed at appropriate places in login. Fixes #408
> Login Error Message Displayed

- app/src/main/res/layout/activity_userprofile.xml
Added ripple effect to UserProfileActivity. Fixes #417
> Ripple effect added to Create User

- README.md
> Added Open Source Libraries Used

- README.md
closes #423 
@WomenWhoCode/android-reviewers :)
> add reviewers to read me #423

- app/src/main/java/com/womenwhocode/womenwhocode/activities/LoginEmailActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/UserProfileActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/AddPostDialogFragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- app/src/main/java/com/womenwhocode/womenwhocode/utils/LocationProvider.java
@WomenWhoCode/android-reviewers
#425
> Remove Toasts that are commented out

- app/src/main/java/com/womenwhocode/womenwhocode/activities/SignUpEmailActivity.java
- app/src/main/res/values/strings.xml
@shehbashahab  @zassmin  Added feedback for when user creation fails either due to unavailability of network or due to some internal error. Solves #427
> Added feedback on user creation fail

- app/src/main/java/com/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/TimelineActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/adapters/ChatListAdapter.java
- app/src/main/java/com/womenwhocode/womenwhocode/adapters/FeaturesAdapter.java
- app/src/main/java/com/womenwhocode/womenwhocode/adapters/PostsAdapter.java
- app/src/main/java/com/womenwhocode/womenwhocode/adapters/TimelineAdapter.java
- app/src/main/java/com/womenwhocode/womenwhocode/fragments/Question1Fragment.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- Fix Gradle version
- Fix gradle - wrapper version
- Fixed #380 Added placeholder 
I have added the launcher icon(WWC logo) of the app as the placeholder image.
- Images in the posts and timeline were not re-sized 
so added auto-fit and center crop also.
> Some Fixes

- app/src/main/java/com/womenwhocode/womenwhocode/activities/EventDetailsActivity.java
- app/src/main/java/com/womenwhocode/womenwhocode/activities/FeatureDetailsActivity.java
- app/src/main/res/values/strings.xml
Apologies for the very late response on this. This PR solves the issue referred [here](https://github.com/WomenWhoCode/WomenWhoCode/issues/433)
> Fix in hardcode of strings closes #433
